'use client'
import './globals.css'
import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { usePathname } from 'next/navigation'
import axios from 'axios'
import {useRouter} from "next/navigation";
interface UserData {
  username: string;
  email: string;
}

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const router = useRouter()

  const pathName = usePathname()
  let [data,setData]=React.useState<UserData>({} as UserData)
  React.useEffect(()=>{
    const getUserDetails = async () => {
      const res = await axios.get('/api/users/me')
      console.log(res.data);
      setData(res.data.data)
    }
    getUserDetails()
  },[])

  const logout = async () => {
    try {
        await axios.get('/api/users/logout')
        // toast.success('Logout successful')
        router.push('/login')
    } catch (error:any) {
        console.log(error.message);
        // toast.error(error.message)
    }
}
  return (
    <html lang="en">








      <body className={inter.className}>

        {
          pathName != "/login" && pathName != "/signup" && pathName!="/resetpassword" && pathName!="/verifyemail"?
            <nav className="navbar">
              <div className="navbar-container container">
                <input type="checkbox" name="" id="" />
                <div className="hamburger-lines">
                  <span className="line line1"></span>
                  <span className="line line2"></span>
                  <span className="line line3"></span>
                </div>
                <ul className="menu-items">
                  <li><a href="/">Home</a></li>
                  <li><a href="/profile">Hello'{!data.username ?"user":data.username}</a></li>
                  <li><a onClick={logout} style={{cursor: "pointer"}}>Logout</a></li>
                </ul>
                <h1 className="logo">Navbar</h1>
              </div>
            </nav>
            :
            <></>
        }
        {children}
      </body>
    </html>
  )
}
